# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'WechatDemo' do

end

target 'WechatDemoTests' do

end

target 'WechatDemoUITests' do

end

pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.7'

